apiVersion: apps/v1
kind: Deployment
metadata: 
    name: node-deployment
spec:
    selector: 
      matchLabels:
        app: node
    replicas: 2
    template:
      metadata:
        labels:
          app: node
      spec:
        containers:
        - name: node
          image: node-app:latest
          imagePullPolicy: Never # pour éviter que minikube prend les images à partir de github et prend les image localment
          ports:
          - containerPort: 3000
          args: ["node", "main.js"]
          env: #injecter la bonne adresse Redis dans le pod via une variable d’environnement pour accèder via le bon nom du service Kubernetes
            - name: REDIS_URL
              value: "redis://redis-master:6379"
            - name: REDIS_REPLICAS_URL
              value: "redis://redis-rep-service:6379"
        